### ISSUE TITLE
Dust Map Installation Not Working

### ISSUE THREAD

**Issue by djhoover717** [jobovy/mwdust#17]
I am a second-year undergraduate currently working on a project that involves the installation of the mwdust package.  The installation commands are intended for Unix, yet I am trying to run them on a Windows machine.  When I run setup.py, I get the following error message: "FileNotFoundError: [WinError 2] The system cannot find the file specified".  Is there another way to install mwdust?

**Comment by jobovy** [comment]
This may happen if you don't have `wget` installed or if Python isn't able to call it (can you do `import os; os.system('wget')`?). Otherwise, did you make sure to set the `DUST_DIR` environment variable?

**Comment by djhoover717** [comment]
I still get the same error after installing `wget`.  I defined `DUST_DIR` as an environment variable with its value equal to a file path to a DUST_DIR folder.  However, when I ran `os.environ()`, `DUST_DIR` did not show up, so I defined `DUST_DIR` as an environment variable using `os.environ()`.  Is there a problem with my initialization of `DUST_DIR`?

**Comment by jobovy** [comment]
I think is should work to do
```
os.environ['DUST_DIR']= 'FILEPATH'
```
but I'm not sure. Did you put this in the `setup.py` file? If you just do this in a Python session, I don't think it transfers to other sessions.

When you defined the variable, did you export it? How exactly you define an environment variable in Windows depends on what shell you are using. These installation instructions for a different code might help with defining environment variables on Windows: https://docs.galpy.org/en/v1.6.0/installation.html#installing-from-source-on-windows

Note that if you are using `sudo` to install, you have to add the `-E` option to make sure the environment variables are passed.

**Comment by djhoover717** [comment]
I am using Python to install.  I switched to defining environment variables by using the `set` command in Anaconda.  Does that require some sort of export?

**Comment by jobovy** [comment]
This might help?

https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows

**Comment by djhoover717** [comment]
OK, I think my problem is almost solved.  I was about to download the SFD and Drimmel maps, but not the Marshall maps.  For some reason, `gunzip` could not find the file specified.  Is there a way to use `wget` to perform the same function as `gunzip` for that data table?

**Comment by jobovy** [comment]
I don't quite understand how you are doing the installation now, are you just downloading the files manually? If so, you can just put them in the directory structure shown in the [dust data section of the README](https://github.com/jobovy/mwdust#dust-data) and run the installation with ``--no-downloads``.

I don't see how you could get a "Connection failed...unknown error." error when running the ``chown`` command, that should just be trying to change the ownership of the file, not do anything that requires a connection!

**Comment by arseneausm** [comment]
Yeah, `curl` is installed natively on Windows, so that might be the way to go. 

Adding that flag does make the download work, but there are still some unix-specific C code in the install part of the script. I'm not sure how much of that is actually an issue though and how much of that is just a messed up Visual C install on my system (for example, `unistd.h` can be changed to `io.h` on windows systems and should work the same).

**Comment by jobovy** [comment]
Thanks, that's useful info. I'll leave this open for now in case somebody else wants to take a crack at fixing the `wget` commands either by replacing them with `curl` or by just doing the `shell=WIN32` fix.

Yeah, the C code would require more changes to compile on Windows. The C code is only used for the `SFD` map, so the rest of the code should be able to run on Windows with no issues (I think). So splitting the work into

1. Fix downloads
2. Fix C compilation

would make sense, because 1. is _much_ easier.

**Comment by jobovy** [comment]
Okay, I couldn't help myself and did some work on this. I replaced all `wget` calls with `cURL` and otherwise tried to update the `setup.py` script to run on Windows. I think it should now work, provided that `gzip` exists, which can be obtained, e.g., through installing `7zip`. These changes are presented in #23.

However, as discussed in #23, `mwdust` is still very limited on Windows, because the SFD map doesn't work until we fix the compilation issues and the hierarchical HEALPIx-based maps don't work because `healpy` isn't readily accessible on Windows. So the code is still quite limited on Windows. But I would nevertheless appreciate it if you could test the installation on Windows (starting from a clean `DUST_DIR`, so the downloads are actually attempted).

**Comment by jobovy** [comment]
#24 added support for compiling the SFD code on Windows, so the entire package can now be installed on Windows. `healpy` still doesn't work on Windows AFAIK, but that's not our problem, so this issue is now closed. Note that @henrysky is working on getting the necessary `healpy` functionality to work on Windows, so that might also be fixed soon.
