### ISSUE TITLE
Installing on Windows?

### ISSUE THREAD

**Issue by jimclark** [jobovy/mwdust#19]
I'm trying to get mwdust installed on my Windows machine (so I can install isoclassify, so I can run a teammate's code) and am running into a snag on compiling the SFD C code.  There are a couple of Unix-specific parts of the code; one of them is [including unistd.h](https://github.com/jobovy/mwdust/blob/542ba0374ffd79e926d147abee9a484ccef077cd/mwdust/util/SFD_CodeC/subs_inoutput.c#L2), which I found [a workaround patch for](https://github.com/win32ports/unistd_h/blob/master/unistd.h), but Microsoft Visual C does not like ['m'](https://github.com/jobovy/mwdust/blob/542ba0374ffd79e926d147abee9a484ccef077cd/setup.py#L469), and the StackOverflow advice to either remove that reference or replace it with 'msvcrt' has not worked.

Anything else I might try, or is this a sign to get my Linux box up and running again? :)

Thanks,
Jim

**Comment by jobovy** [comment]
Hi Jim,

Thanks for raising this issue. Yes, on Windows it's not necessary (and even wrong to include the math library as 'm'). I think it should work to just remove that line from the `setup.py` file, is that what you mean that you tried and it doesn't work? If you can get it to compile like this, then it's probably pretty easy to get `mwdust` to compile on Windows (I'll just have to find time to load my Windows VM...), otherwise it might be more difficult.

As an alternative, I hear good things about the Windows Subsystem for Linux...

**Comment by jimclark** [comment]
When I delete the ["libraries=..." line](https://github.com/jobovy/mwdust/blob/542ba0374ffd79e926d147abee9a484ccef077cd/setup.py#L472) and run setup, it compiles all of the different subs_X.c files into .obj but then fails with the message "LINK : error LNK2001: unresolved external symbol PyInit_sfd_c".

**Comment by jobovy** [comment]
Thanks, that's useful and that makes sense to me. I know how to deal with that (having solved the Windows issues from one of my other libraries), but it will likely be a while before I get to implementing that. WSL of something like cygwin (if that still exists??) is for now your best bet.

To gauge Windows more broadly: if others are interested in Windows support, please upvote 👍 the original comment in this thread (click on the smiley).

**Comment by jobovy** [comment]
#26 added Windows support for the SFD compilation, so this issue can now be closed.
