### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by emmalouden** [jobovy/mwdust#25]
Hello, I am running into issues with installation of mwdust. Running the setup.py script for mwdust gives:
running bdist_egg
running egg_info
writing mwdust.egg-info/PKG-INFO
writing dependency_links to mwdust.egg-info/dependency_links.txt
writing requirements to mwdust.egg-info/requires.txt
writing top-level names to mwdust.egg-info/top_level.txt
reading manifest template '[MANIFEST.in](https://manifest.in/)'
adding license file 'LICENSE'
adding license file 'AUTHORS.txt'
writing manifest file 'mwdust.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
running build_ext
building 'sfd_c' extension

After the last step listed, I got a long error attached to this message. I am running it on an M1 mac, but I also tested it on an intel chip mac to troubleshoot. Do you have any insight into this issue?

[isoclassify error.txt](https://github.com/jobovy/mwdust/files/10798809/isoclassify.error.txt)

**Comment by jobovy** [comment]
Is this the output from running on your M1 mac? I'm asking, because the output lists the architecture as `x86_64`, while on an M1 mac you should have `arm64` natively (unless you are using Rosetta perhaps, I've never used it). Anyway, the code compiles fine on my M1 mac and on the Intel mac used in the GitHub Actions CI, so I suspect the error lies with your system. Some googling reveals that the likely issue is an inconsistency in your Xcode installation (e.g., https://developer.apple.com/forums/thread/722490), so you might have to nix it and re-install. Your output also mentions `macosx-10.9`, which is a ten-year old version of Mac OS X, so I suspect that you may be carrying around files from an old laptop?

**Comment by emmalouden** [comment]
Yep---it was inconsistency in Xcode. Thank you!!
