### ISSUE TITLE
raise IOError('SFD/C module not found')

### ISSUE THREAD

**Issue by akritiasto** [jobovy/mwdust#8]
I am using Python 3.6.3 :: Anaconda custom (64-bit).I have installed mwdust using __**" sudo python3 setup.py install --no-downloads"_**_
The dust data is also downloaded in the DUST_DIR.On importing mwdust I am getting the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akriti/dust/mwdust-master/mwdust/__init__.py", line 1, in <module>
    from mwdust.SFD import SFD
  File "/home/akriti/dust/mwdust-master/mwdust/SFD.py", line 7, in <module>
    from mwdust.util.read_SFD import read_SFD_EBV
  File "/home/akriti/dust/mwdust-master/mwdust/util/read_SFD.py", line 27, in <module>
    raise IOError('SFD/C module not found')
OSError: SFD/C module not found
Also, if I close the terminal and open a new one i need to run setup.py again otherswise it says:
ModuleNotFoundError: No module named 'mwdust'

**Comment by jobovy** [comment]
Bit of a guess here, but I think the issue might be that you are running the code in the ``home/akriti/dust/mwdust-master/`` directory. If you do that, the local version will be loaded, rather than the one you installed. And the local version doesn't have access to the ``SFD/C`` module.

If that's not the issue, then something must have gone wrong during the installation process. Try installing again and comment with the output from the installation here (use [pastebin](https://pastebin.com/) for long outputs). Make sure you rebuild the entire code when doing this, you may have to remove the ``build/`` directory to achieve this.

**Comment by akritiasto** [comment]
Hello.
Thank you for the valuable input! I tried running it from another directory
and was able to import it and run it successfully using spyder(python
3.6).However it is still not installed in python3 when I am running from
the terminal.I think that is just an installation issue and will probably
be resolved if I install mwdust again for python3.Also I was wondering in
what units should the distance be inputed when using mwdust.eg in the line :



*drimmel(60.,0.,3.)*

Could you tell me that.

Regards

Akriti

**Comment by jobovy** [comment]
The distance should be in kpc (``?drimmel`` gives the documentation for the ``__call__`` function).

**Comment by jobovy** [comment]
I hope this issue is now resolved. If yes, please close it; if no, please let me know what the remaining issue os.

**Comment by akritiasto** [comment]
Sorry for the late  reply and thank you for the help.I have closed the
issue.I have another doubt though.What will the following line return ,the
E(B-V) or the A(λ). (the absolute extinction at any wavelength).?

sfd= mwdust.SFD(filter='WFC3 F218W')

a5=sfd(l,b,dlk)
Could you tell me what to interpret of the result.

-akriti

**Comment by jobovy** [comment]
When you specify a filter, the extinction itself A(lambda) is returned. If ``filter=None`` or you just don't specify the filter, E(B-V) is returned.
